# Generated by Django 3.0.1 on 2020-01-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
